### ISSUE TITLE
Feature request: Load Balancer with Caddy/Nginx/Traefik

### ISSUE THREAD

**Issue by scart88** [rails/mrsk#2]
[Caddy](https://caddyserver.com/v2) would be an excellent, fast and easy way to add a load balancer when multiple servers are used. On top of that, it generates Automatic SSL/HTTPS certificates, making life easier for many...

In the config we could specify the load balancer server and here is a basic example.
#### /config/deploy.yml
```yaml
service: hey
image: 37s/hey
load_balancer:
  host: example.com
  server: xxx.xxx.xxx.xxx
  encode: gzip br
servers:
  - xxx.xxx.xxx.xxx
  - xxx.xxx.xxx.xxx
  ....
```

A Caddy server will be configured on the load balancer server and will reverse proxy to all hosts.
```
docker run -d --name p-caddy --restart always \ 
--network host -v /home/caddy/Caddyfile:/etc/caddy/Caddyfile -v /home/caddy-data:/data caddy
```
#### Caddyfile
```
example.com # Your site's domain name

# Compress responses according to Accept-Encoding headers
encode gzip zstd

# Load balance between three backends with custom health checks
reverse_proxy 10.0.0.1:9000 10.0.0.2:9000 10.0.0.3:9000 {
	lb_policy       random_choose 2
	health_path     /ok
	health_interval 10s
}
```
