### ISSUE TITLE
Allow bastion SSH server

### ISSUE THREAD

**Issue by dhh** [rails/mrsk#7]
SSHKit can configure Netssh to use a bastion SSH server. We should change our setup so that passes through. We could change the top level ssh_user configuration option to be:

```yaml
ssh:
  user: app
  # whatever is needed for bastion
```
